apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  selector:
    app: demo
    version: blue   # switch to green when testing rollout
  ports:
    - port: 80
      targetPort: 3000

